### PR TITLE
docs: minor fixes and removals

### PR DESCRIPTION
**Pull request by fnchooft**
Fixed minor typos.

Adapted the section about Calculations to alert the developer about the fact, that Aggregations, ( which are needed for Calculations) are not supported in the SQLite-layer.

### Contributor checklist
- Only textual changes in README - no code changes
- [No] Bug fixes include regression tests
- [No] Features include unit/acceptance tests

### CODE REVIEW

**Comment by zachdaniel** [comment]
Small adjustment: aggregates are not needed for calculations. Calculations should work fine with ash_sqlite.

**Comment by fnchooft** [comment]
Hi Zach, great libraries!

I will fix the text - as I just started learning Ash - forgive my ignorance.

As I jumped directly to the SQLite-howto ( instead of going through the Postgres one ) I did not understand where total_tickets and open_tickets came from.

Would you have another ( better, smaller ) example in Mind for a Calculation?

Kind regards,

Fabian

**Comment by zachdaniel** [comment]
🤔 I would just use the `full_name` calculation example, even though it doesn't relate to the current resource. i.e

```elixir
calculate :full_name, :string, expr(first_name <> " " <> last_name)
```

**Comment by fnchooft** [comment]
@zachdaniel - I added a working calculation using the status,subject fields.

Kind regards,
Fabian

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
